name: Deploy to IONOS

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama se llama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 1. Entrar a la carpeta 'frontend', instalar y compilar
      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # 2. Subir la carpeta 'dist' a IONOS
      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./frontend/dist/
          server-dir: ./